apply plugin: 'com.android.application'

android {
    namespace 'com.lofidashboard.app'
    compileSdk 33

    defaultConfig {
        applicationId "com.lofidashboard.app"
        minSdk 19
        targetSdk 28
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
